### PR TITLE
change to using array functions

### PR DESCRIPTION
**Pull request by wiktor-jurek**
there's absolutely no need for this and it may not even work but it's slightly more readable

### CODE REVIEW

**Review by Blair-Mckenzie — COMMENTED** [review]
The code can definely be tidied up, but text content doesn't work as it returns something like:
(textContent: "\n    \n    CS982: Big Data Technologies\n") which won't match a class name.

**Comment by wiktor-jurek** [comment]
There are [good reasons](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innerhtml) to use textContent as opposed to InnerHTML, so perhaps it's in our best interest to migrate from the old system?

**Comment by Blair-Mckenzie** [comment]
Yeah absolutely, looked at that exact link already. It's better for safety purposes was originally just trying to get a working solution

**Comment by wiktor-jurek** [comment]
Time to make this an Ironclad myplace killer 👿

**Comment by Blair-Mckenzie** [comment]
Glad to hear it, gonna try add a user selection next so there will be no need to hard code anything. Will try to get textContent to work first.

**Pull request merged**
